name: simplefund
version: 1

handlers:
- url: /scripts
  static_dir: dist/scripts

- url: /styles
  static_dir: dist/styles

- url: /views
  static_dir: dist/views

- url: /fonts
  static_dir: dist/fonts


- url: /images
  static_dir: dist/images


libraries:
- name: MySQLdb
  version: "1.2.3"

- name: pylibmc
  version: "1.4.2"